#!/usr/bin/env python3
import sys
import fire
import paramiko
import json

def deploy(command):
  severHost = json.load(open('py-ssh.json'));
  _command = command;
  _host = severHost['host'];
  _username = severHost['user'];
  _password = severHost['password'];
  _dir = severHost['dir'];

  client = paramiko.SSHClient();
  client.load_system_host_keys();
  client.set_missing_host_key_policy(paramiko.AutoAddPolicy());
  client.connect(
    _host,
    username=_username,
    password=_password
  );
  cd_dir = "cd %s; " % _dir;
  command_list = command.split('\n');
  for cmd in command_list:
    if cmd == '':
      continue;
    print("[command]: %s" % cmd);
    stdin, stdout, stderr = client.exec_command(cd_dir + cmd);
    exit_status = stdout.channel.recv_exit_status();
    if exit_status == 0:
      print('[success]: %s' % stdout.read().decode("utf-8"));
    else:
      print("[status] %s" % exit_status);
      sys.exit('[error]: %s' % stderr.read().decode("utf-8"));

if __name__ == '__main__':
  fire.Fire(deploy);